@startuml

title MSI Broadcasts - Class Diagram

class MSI {
  id: string
  payload: string
  startDateInclusive: timestamp
  endDateExclusive: timestamp
  send()
  cancel()
}
class SARBroadcast
class MetBroadcast
class NavWarningBroadcast

enum Priority {
  SAFETY
  URGENCY
  DISTRESS
}
enum Status {
  CREATED
  SCHEDULED
  ACTIVE
  FINISHED
  CANCELLED
}
enum IntervalHours {
  1
  2
  3
  4
  5
  6
  12
  18
  24
  30
  36
  48
  60
  72
  96
  120
}

interface Repetition 
class Twice
class RepeatTillCancelled

MSI -- "0..1" Repetition
Repetition <|-- Twice
Repetition <|-- RepeatTillCancelled
Twice -- "1" IntervalHours
RepeatTillCancelled  -- "1" IntervalHours

class MetArea {
  metAreaNo: integer
}
class NavArea {
  navAreaNo: integer
}
class CoastalWarningArea {
  letter: char
}

interface SARBroadcastArea

class Circle {
  lat: decimal
  lon: decimal
  radiusNm: decimal
}
class Rectangle {
  minLat: decimal
  leftLon: decimal
  heightDegrees: decimal
  widthDegrees: decimal
}
interface Geometry
interface NavWarningArea
interface MeteorologicalArea

Geometry <|-- Circle
Geometry <|-- Rectangle

NavWarningArea <|-- NavArea
NavWarningArea <|-- CoastalWarningArea
NavWarningArea <|-- Geometry

MeteorologicalArea <|-- Geometry
MeteorologicalArea <|-- CoastalWarningArea
MeteorologicalArea <|-- MetArea

SARBroadcastArea <|-- Geometry
SARBroadcastArea <|-- NavArea

MSI <|-- SARBroadcast
MSI <|-- MetBroadcast
MSI <|-- NavWarningBroadcast

SARBroadcast  -- "0..1" SARBroadcastArea
MetBroadcast  -- "1" MeteorologicalArea
NavWarningBroadcast  -- "1" NavWarningArea

MSI -- "1" Priority
MSI -- "1" Status

@enduml
