@startuml

title MSI Broadcasts - Class Diagram

class MSI {
  id: string
  payload: string
  startDate: timestamp
  endDate: timestamp
  send()
  cancel()
}

class SARBroadcast
interface NonSARBroadcast
class MetBroadcast {
  isForecast: boolean
}
class NavBroadcast 
class PiracyBroadcast

enum SARPriority {
  SAFETY
  URGENCY
  DISTRESS
}
enum NonSARPriority {
  SAFETY
  URGENCY
}
enum Status {
  CREATED
  SCHEDULED
  ACTIVE
  FINISHED
  CANCELLED
}
enum IntervalHours {
  1
  2
  3
  4
  5
  6
  12
  18
  24
  30
  36
  48
  60
  72
  96
  120
}

interface Repetition 
class RepeatOnce
class RepeatTillCancelled

MSI -- "0..1" Repetition
Repetition <|-- RepeatOnce
Repetition <|-- RepeatTillCancelled
RepeatOnce -- "1" IntervalHours
RepeatTillCancelled  -- "1" IntervalHours

class MetArea {
  metAreaNo: integer
}
class NavArea {
  navAreaNo: integer
}
class CoastalWarningArea {
  navAreaNo: integer
  letter: char
}

enum SubjectIndicator {
  NAVIGATIONAL_WARNINGS
  METEOROLOGICAL_WARNINGS
  ICE_REPORTS
  SAR_INFO_AND_PIRACY_WARNINGS
  METEOROLOGICAL_FORECASTS
  NOT_USED
  SATNAV_MESSAGES
  OTHER_ELECTRONIC_NAVAID_MESSAGES
  OTHER_NAVIGATIONAL_WARNINGS
  PILOT_SERVICE_MESSAGES
  AIS
  LORAN_MESSAGES
  SPECIAL_SERVICES_V
  SPECIAL_SERVICES_W
  SPECIAL_SERVICES_X
  SPECIAL_SERVICES_Y
  NO_MESSAGES_ON_HAND
}
CoastalWarningArea -- "1" SubjectIndicator
 
interface SARBroadcastArea

class Circle {
  lat: decimal
  lon: decimal
  radiusNm: decimal
}
class Rectangle {
  minLat: decimal
  leftLon: decimal
  heightDegrees: decimal
  widthDegrees: decimal
}
interface Geometry
interface NavOrPrivacyBroadcastArea
interface MetBroadcastArea

Geometry <|-- Circle
Geometry <|-- Rectangle

NavOrPrivacyBroadcastArea <|-- NavArea
NavOrPrivacyBroadcastArea <|-- CoastalWarningArea
NavOrPrivacyBroadcastArea <|-- Geometry

MetBroadcastArea <|-- Geometry
MetBroadcastArea <|-- CoastalWarningArea
MetBroadcastArea <|-- MetArea

SARBroadcastArea <|-- Geometry
SARBroadcastArea <|-- NavArea

MSI <|-- SARBroadcast
MSI <|-- NonSARBroadcast
NonSARBroadcast <|-- MetBroadcast
NonSARBroadcast <|-- NavBroadcast
NonSARBroadcast <|-- PiracyBroadcast

SARBroadcast  -- "0..1" SARBroadcastArea
MetBroadcast  -- "1" MetBroadcastArea
NavBroadcast  -- "1" NavOrPrivacyBroadcastArea
PiracyBroadcast  -- "1" NavOrPrivacyBroadcastArea

NonSARBroadcast -- "1" NonSARPriority
SARBroadcast -- "1" SARPriority
MSI -- "1" Status

@enduml
